### ISSUE TITLE
To-do app for CodePath Android Observer Group

### ISSUE THREAD

**Issue by withlovee** [withlovee/VeeTodo#1]
Here it is @CoderRed99 :)

**Comment by CoderRed99** [comment]
Got it! Thanks

**Comment by withlovee** [comment]
@CoderRed99 
Hi Dianna, I added the demo video in the README file, you can see it here:
https://github.com/withlovee/VeeTodo

I'm not sure whether I should submit the video here. Could you reply once you get it?

**Comment by CoderRed99** [comment]
That's fine either way I got it! Isn't licecap cool. :)

**Comment by withlovee** [comment]
Yes it is! Simple is the best. :smile:
